// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-3k_n8NTrvX3haRc1cNW3hCgZ9j267l0',
    appId: '1:991437817866:web:7c96007d4469395b0c37f3',
    messagingSenderId: '991437817866',
    projectId: 'flavors-with-firebase',
    authDomain: 'flavors-with-firebase.firebaseapp.com',
    storageBucket: 'flavors-with-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaXpygncxWyTKOSHHshPq9lFnTMRPAgOs',
    appId: '1:991437817866:android:3d509b4055b011610c37f3',
    messagingSenderId: '991437817866',
    projectId: 'flavors-with-firebase',
    storageBucket: 'flavors-with-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9-aMi95GbSEn-bPZV1N8_vJMiXQnJvg',
    appId: '1:991437817866:ios:9f04b21de69ef8330c37f3',
    messagingSenderId: '991437817866',
    projectId: 'flavors-with-firebase',
    storageBucket: 'flavors-with-firebase.appspot.com',
    iosClientId: '991437817866-8i11q39q59lkb0dgn02p2l2asq13o83c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flavorsWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd9-aMi95GbSEn-bPZV1N8_vJMiXQnJvg',
    appId: '1:991437817866:ios:c06ee8beb5e887f10c37f3',
    messagingSenderId: '991437817866',
    projectId: 'flavors-with-firebase',
    storageBucket: 'flavors-with-firebase.appspot.com',
    iosClientId: '991437817866-eg3bu895j918uoio0pat290mcs3kq965.apps.googleusercontent.com',
    iosBundleId: 'com.example.flavorsWithFirebase.RunnerTests',
  );
}
